x-template: &base
  build: .
  volumes:
    - .:/app
  working_dir: /app
  init: true
  network_mode: service:broker
  depends_on:
    - broker
  environment:
    MQTT_LIMIT: ${MQTT_LIMIT}
    PUB_INTERVAL: ${PUB_INTERVAL}
    MQTT_QOS: ${MQTT_QOS}

services:
  broker:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  sub:
    <<: *base
    command: /usr/bin/time -v python3 -m benchmarks.${SUB}_sub

  pub:
    <<: *base
    depends_on:
      - sub
    command: /usr/bin/time -v python3 -m benchmarks.${PUB}_pub
