x-template: &base
  build: .
  volumes:
    - .:/app
  working_dir: /app
  init: true
  network_mode: service:broker

services:
  broker:
    image: eclipse-mosquitto:latest

  py:
    <<: *base
    network_mode: none
    command: python3 -c "import signal; signal.pause()"

  pymosq_sub:
    <<: *base
    command: python3 -m benchmarks.pymosq_sub

#  pymosq_sub_base:
#    <<: *base
#    command: python3 -m benchmarks.pymosq_sub_base

  pymosq_pub:
    <<: *base
    command: python3 -m benchmarks.pymosq_pub
    environment:
      PUB_INTERVAL: 5

  paho_sub:
    <<: *base
    command: python3 -m benchmarks.paho_sub
