x-template: &base
  build: .
  volumes:
    - .:/app
  working_dir: /app
  init: true
  network_mode: service:broker

services:
  broker:
    image: eclipse-mosquitto:latest

  py:
    <<: *base
    command: python3 -c "import signal; signal.pause()"

  pymo_sub:
    <<: *base
    command: python3 -m examples.pymo_sub

  pymo_pub:
    <<: *base
    command: python3 -m examples.pymo_pub

  paho_sub:
    <<: *base
    command: python3 -m examples.paho_sub
