x-template: &base
  build: .
  volumes:
    - ./benchmarks:/app/benchmarks
  working_dir: /app
  init: true
  network_mode: service:broker
  depends_on:
    - broker
  environment:
    MQTT_QOS: ${MQTT_QOS}
    MQTT_LIMIT: ${MQTT_LIMIT:-1000}
    PUB_INTERVAL: ${PUB_INTERVAL:-5}

services:
  broker:
    image: eclipse-mosquitto:latest

  py:
    <<: *base
    network_mode: none
    command: /usr/bin/time -v python3 -c ""

  sub:
    <<: *base
    command: /usr/bin/time -v python3 -m benchmarks.${PREFIX:-pymosq}_sub

  pub:
    image: eclipse-mosquitto:latest
    network_mode: service:broker
    init: true
    depends_on:
      - broker
      - sub
    command: sh -c "sleep 1 && mosquitto_pub -t "benchmark" -n --repeat 3000000 --repeat-delay ${PUB_INTERVAL:-5} --nodelay"
