x-template: &base
  build: .
  volumes:
    - .:/app
  working_dir: /app
  init: true
  network_mode: service:broker
  environment:
#    MQTT_LIMIT: 1000
    MQTT_QOS: 0

services:
  broker:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  sub:
    <<: *base
    depends_on:
      - broker
    command: /usr/bin/time -v python3 -m benchmarks.${PREFIX}_sub

  pub:
    <<: *base
    depends_on:
      - sub
    command: bash -c "/usr/bin/time -v python3 -m benchmarks.${PREFIX}_pub"
